import { PersonModel } from '../models/person.model';
import { UserModel } from '../models/user.model';
import { InstitutionModel } from '../models/institution.model';
import { SeederLog } from '../models/seeder-log.model';
import { Gender, ConsciousnessLevel, PersonStatus, UserRole } from '../enums';
import { buildReportedBy } from '../utils/reporter.utils';
import { logger } from '../lib';

const SEEDER_ID = 'persons-v6';

export const runPersonsSeeders = async (): Promise<void> => {
  try {
    const alreadyRan = await SeederLog.findById(SEEDER_ID);
    if (alreadyRan) {
      logger.info(`Seeder "${SEEDER_ID}" already ran, skipping`);
      return;
    }

    const carlos = await UserModel.findOne({ email: 'carlos.mendez@italiano.org.ar' });
    const laura = await UserModel.findOne({ email: 'laura.garcia@italiano.org.ar' });
    const sofia = await UserModel.findOne({ email: 'sofia.rodriguez@aleman.org.ar' });

    if (!carlos || !laura || !sofia) {
      throw new Error('Required users not found. Run users seeder first.');
    }

    const italiano = await InstitutionModel.findOne({ name: 'Hospital Italiano de Buenos Aires' });
    const aleman = await InstitutionModel.findOne({ name: 'Hospital Alemán' });
    const britanico = await InstitutionModel.findOne({ name: 'Hospital Británico de Buenos Aires' });
    const clinicas = await InstitutionModel.findOne({ name: 'Hospital de Clínicas José de San Martín (UBA)' });
    const mater = await InstitutionModel.findOne({ name: 'Sanatorio Mater Dei' });
    const favaloro = await InstitutionModel.findOne({ name: 'Fundación Favaloro' });
    const guemes = await InstitutionModel.findOne({ name: 'Sanatorio Güemes' });
    const otamendi = await InstitutionModel.findOne({ name: 'Sanatorio Otamendi' });
    const bazterrica = await InstitutionModel.findOne({ name: 'Clínica Bazterrica' });

    if (!italiano || !aleman || !britanico || !clinicas || !mater || !favaloro || !guemes || !otamendi || !bazterrica) {
      throw new Error('Required institutions not found. Run institutions seeder first.');
    }

    await PersonModel.deleteMany({});

    const persons = [
      // ── 4 NNs con match diseñado ───────────────────────────────────────────
      // MATCH-1: hombre atlético con tatuaje de águila + cicatriz en mentón → Marcelo Fuentes
      {
        estimatedAgeMin: 38,
        estimatedAgeMax: 46,
        gender: Gender.MALE,
        height: 1.79,
        weight: 82,
        distinctiveFeatures: 'Contextura atlética. Tatuaje de águila en el antebrazo derecho. Cicatriz en el mentón. Cabello negro corto.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Corrientes 3800, Almagro',
        neighborhood: 'Almagro',
        geoLocation: { type: 'Point' as const, coordinates: [-58.4217, -34.6039] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-02T08:00:00'),
        status: PersonStatus.POTENTIAL_MATCH,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },
      // MATCH-2: mujer joven, cabello castaño corto, piercing oreja izq., lunar en cuello → Luciana Torres
      {
        estimatedAgeMin: 25,
        estimatedAgeMax: 31,
        gender: Gender.FEMALE,
        height: 1.62,
        weight: 55,
        distinctiveFeatures: 'Cabello castaño corto. Piercing en oreja izquierda. Marca de nacimiento en el cuello lado derecho. Vestía ropa informal.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. San Juan 3200, Boedo',
        neighborhood: 'Boedo',
        geoLocation: { type: 'Point' as const, coordinates: [-58.418, -34.628] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-03T17:30:00'),
        status: PersonStatus.POTENTIAL_MATCH,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        assignedTo: 'EAAF',
        createdBy: laura._id,
        identifyingPhotos: [],
      },
      // MATCH-3: mujer joven, cabello largo negro lacio, campera jean, remera blanca → Camila Suárez
      {
        estimatedAgeMin: 22,
        estimatedAgeMax: 28,
        gender: Gender.FEMALE,
        height: 1.63,
        weight: 54,
        distinctiveFeatures: 'Cabello largo lacio negro. Campera de jean corta, remera blanca, pantalón negro. Tatuaje de mariposa en el tobillo derecho. Múltiples aros en las orejas.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Santa Fe 4200, Palermo',
        neighborhood: 'Palermo',
        geoLocation: { type: 'Point' as const, coordinates: [-58.413, -34.577] },
        institution: mater._id,
        dateOfAdmission: new Date('2026-06-01T22:30:00'),
        status: PersonStatus.POTENTIAL_MATCH,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        assignedTo: 'SIFEBU',
        createdBy: laura._id,
        identifyingPhotos: [],
      },
      // MATCH-4: adulto mayor, contextura delgada, pijama a rayas, calvo → Néstor Quiroga
      {
        estimatedAgeMin: 65,
        estimatedAgeMax: 75,
        gender: Gender.MALE,
        distinctiveFeatures: 'Contextura delgada. Pijama a rayas celeste y blanco, descalzo. Manchas de vitíligo en ambas manos y cuello. Calvo con franja de cabello blanco en los costados. Aparenta deterioro cognitivo.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Callao 1500, Recoleta',
        neighborhood: 'Recoleta',
        geoLocation: { type: 'Point' as const, coordinates: [-58.393, -34.587] },
        institution: aleman._id,
        dateOfAdmission: new Date('2026-06-05T08:00:00'),
        status: PersonStatus.POTENTIAL_MATCH,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        assignedTo: 'EAAF',
        createdBy: sofia._id,
        identifyingPhotos: [],
      },

      // ── Agronomia ──────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 30,
        estimatedAgeMax: 40,
        gender: Gender.MALE,
        height: 1.70,
        weight: 72,
        distinctiveFeatures: 'Cabello oscuro rizado. Cicatriz en la ceja izquierda. Vestía ropa de trabajo con manchas de pintura.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. San Martín 3900, Agronomia',
        neighborhood: 'Agronomia',
        geoLocation: { type: 'Point' as const, coordinates: [-58.481, -34.592] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-10T11:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 50,
        estimatedAgeMax: 60,
        gender: Gender.FEMALE,
        height: 1.58,
        distinctiveFeatures: 'Cabello gris corto. Anteojos de marco plateado. Quemadura leve en el dorso de la mano derecha.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. La Plata 500, Agronomia',
        neighborhood: 'Agronomia',
        geoLocation: { type: 'Point' as const, coordinates: [-58.482, -34.594] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-11T09:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Almagro ────────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 38,
        estimatedAgeMax: 48,
        gender: Gender.MALE,
        height: 1.78,
        weight: 80,
        distinctiveFeatures: 'Tatuaje de águila en antebrazo derecho. Cicatriz en mentón.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Tte. Gral. Juan D. Perón 4190, Almagro',
        neighborhood: 'Almagro',
        geoLocation: { type: 'Point' as const, coordinates: [-58.4217, -34.6039] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-03T09:15:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 24,
        estimatedAgeMax: 32,
        gender: Gender.FEMALE,
        height: 1.62,
        weight: 55,
        distinctiveFeatures: 'Cabello castaño corto. Piercing en oreja izquierda. Marca de nacimiento en cuello.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Tte. Gral. Juan D. Perón 4190, Almagro',
        neighborhood: 'Almagro',
        geoLocation: { type: 'Point' as const, coordinates: [-58.4217, -34.6039] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-03T14:45:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        assignedTo: 'EAAF',
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Balvanera ──────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 14,
        estimatedAgeMax: 19,
        gender: Gender.FEMALE,
        height: 1.60,
        distinctiveFeatures: 'Guardapolvo blanco, pollera gris, mochila verde. Frenillos metálicos. Marca de nacimiento marrón en la mejilla izquierda.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Córdoba 2351, Balvanera',
        neighborhood: 'Balvanera',
        geoLocation: { type: 'Point' as const, coordinates: [-58.3978, -34.5983] },
        institution: clinicas._id,
        dateOfAdmission: new Date('2026-06-03T14:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 45,
        estimatedAgeMax: 55,
        gender: Gender.MALE,
        height: 1.73,
        weight: 85,
        distinctiveFeatures: 'Barba descuidada gris. Tatuaje de ancla en la mano izquierda. Vestía campera impermeable azul.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Rivadavia 3100, Balvanera',
        neighborhood: 'Balvanera',
        geoLocation: { type: 'Point' as const, coordinates: [-58.401, -34.599] },
        institution: clinicas._id,
        dateOfAdmission: new Date('2026-06-08T07:45:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Barracas ───────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 28,
        estimatedAgeMax: 36,
        gender: Gender.MALE,
        height: 1.75,
        weight: 70,
        distinctiveFeatures: 'Cabello negro liso, corte moderno. Tatuaje de texto en el cuello. Zapatillas deportivas blancas.',
        consciousnessLevel: ConsciousnessLevel.UNCONSCIOUS,
        address: 'Perdriel 74, Barracas',
        neighborhood: 'Barracas',
        geoLocation: { type: 'Point' as const, coordinates: [-58.3735, -34.6398] },
        institution: britanico._id,
        dateOfAdmission: new Date('2026-06-04T03:10:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 55,
        estimatedAgeMax: 65,
        gender: Gender.FEMALE,
        distinctiveFeatures: 'Contextura robusta. Cabello canoso en rodete. Vestía bata de tela a flores. Sin calzado.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Montes de Oca 200, Barracas',
        neighborhood: 'Barracas',
        geoLocation: { type: 'Point' as const, coordinates: [-58.375, -34.641] },
        institution: britanico._id,
        dateOfAdmission: new Date('2026-06-06T15:20:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Belgrano ───────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 60,
        estimatedAgeMax: 70,
        gender: Gender.FEMALE,
        height: 1.57,
        weight: 62,
        distinctiveFeatures: 'Cabello rubio teñido corto. Anteojos de sol oscuros sin marco de receta. Bolso de cuero negro. Parece desorientada.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Cabildo 2500, Belgrano',
        neighborhood: 'Belgrano',
        geoLocation: { type: 'Point' as const, coordinates: [-58.461, -34.563] },
        institution: aleman._id,
        dateOfAdmission: new Date('2026-06-07T10:15:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        assignedTo: 'SIFEBU',
        createdBy: sofia._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 20,
        estimatedAgeMax: 28,
        gender: Gender.MALE,
        height: 1.82,
        distinctiveFeatures: 'Alto y delgado. Cabello castaño, barba corta. Auriculares alrededor del cuello. Vestía ropa deportiva.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Monroe 2500, Belgrano',
        neighborhood: 'Belgrano',
        geoLocation: { type: 'Point' as const, coordinates: [-58.463, -34.562] },
        institution: bazterrica._id,
        dateOfAdmission: new Date('2026-06-09T19:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── La Boca ────────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 30,
        estimatedAgeMax: 40,
        gender: Gender.MALE,
        height: 1.68,
        weight: 68,
        distinctiveFeatures: 'Piel morena, cabello oscuro muy corto. Tatuaje de nombre "Gloria" en el pecho. Vestía remera de fútbol celeste y blanca.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Pedro de Mendoza 1800, La Boca',
        neighborhood: 'La Boca',
        geoLocation: { type: 'Point' as const, coordinates: [-58.363, -34.636] },
        institution: britanico._id,
        dateOfAdmission: new Date('2026-06-05T13:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 18,
        estimatedAgeMax: 25,
        gender: Gender.FEMALE,
        height: 1.65,
        distinctiveFeatures: 'Cabello colorado, corte pixie. Múltiples piercings en ambas orejas. Mochila bordó. Zapatillas de plataforma.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Caminito 200, La Boca',
        neighborhood: 'La Boca',
        geoLocation: { type: 'Point' as const, coordinates: [-58.362, -34.638] },
        institution: britanico._id,
        dateOfAdmission: new Date('2026-06-07T22:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Boedo ─────────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 65,
        estimatedAgeMax: 75,
        gender: Gender.MALE,
        distinctiveFeatures: 'Hombre mayor, contextura delgada. Cabello blanco escaso. Bastón de madera. Vestía traje marrón muy deteriorado.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. San Juan 3600, Boedo',
        neighborhood: 'Boedo',
        geoLocation: { type: 'Point' as const, coordinates: [-58.42, -34.629] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-04T08:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        assignedTo: 'EAAF',
        createdBy: sofia._id,
        identifyingPhotos: [],
      },

      // ── Caballito ──────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 33,
        estimatedAgeMax: 42,
        gender: Gender.FEMALE,
        height: 1.66,
        weight: 60,
        distinctiveFeatures: 'Cabello rubio oscuro, ondulado, largo hasta los hombros. Cicatriz de operación en el abdomen. Vestía pijama hospitalario.',
        consciousnessLevel: ConsciousnessLevel.SEDATED,
        address: 'Av. Rivadavia 5800, Caballito',
        neighborhood: 'Caballito',
        geoLocation: { type: 'Point' as const, coordinates: [-58.442, -34.619] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-02T23:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Ministerio Público Fiscal CABA',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 55,
        estimatedAgeMax: 65,
        gender: Gender.MALE,
        height: 1.72,
        weight: 90,
        distinctiveFeatures: 'Contextura robusta. Bigote canoso. Tatuaje militar en el hombro derecho. Vestía ropa deportiva gris.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Acoyte 100, Caballito',
        neighborhood: 'Caballito',
        geoLocation: { type: 'Point' as const, coordinates: [-58.441, -34.618] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-10T06:45:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Chacarita ──────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 35,
        estimatedAgeMax: 45,
        gender: Gender.MALE,
        height: 1.76,
        weight: 78,
        distinctiveFeatures: 'Cabello castaño oscuro corto. Barba de varios días. Tatuaje de reloj de arena en el antebrazo izquierdo. Ropa de trabajo.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Corrientes 6200, Chacarita',
        neighborhood: 'Chacarita',
        geoLocation: { type: 'Point' as const, coordinates: [-58.454, -34.584] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-06T08:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Coghlan ────────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 70,
        estimatedAgeMax: 80,
        gender: Gender.MALE,
        distinctiveFeatures: 'Contextura delgada. Cabello blanco peinado. Andador metálico. Vestía camisa a cuadros y pantalón de vestir.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Holmberg 2700, Coghlan',
        neighborhood: 'Coghlan',
        geoLocation: { type: 'Point' as const, coordinates: [-58.472, -34.566] },
        institution: aleman._id,
        dateOfAdmission: new Date('2026-06-08T10:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        assignedTo: 'SIFEBU',
        createdBy: sofia._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 40,
        estimatedAgeMax: 50,
        gender: Gender.FEMALE,
        height: 1.61,
        weight: 65,
        distinctiveFeatures: 'Cabello castaño rojizo, corte a los hombros. Pecas en la nariz y mejillas. Vestía ropa casual de colores claros.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Manuela Pedraza 3200, Coghlan',
        neighborhood: 'Coghlan',
        geoLocation: { type: 'Point' as const, coordinates: [-58.473, -34.567] },
        institution: otamendi._id,
        dateOfAdmission: new Date('2026-06-11T14:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Colegiales ────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 22,
        estimatedAgeMax: 30,
        gender: Gender.MALE,
        height: 1.80,
        weight: 74,
        distinctiveFeatures: 'Cabello largo castaño recogido en moño. Barba larga descuidada. Mochila con parches de bandas. Vestía ropa de colores oscuros.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Dorrego 1800, Colegiales',
        neighborhood: 'Colegiales',
        geoLocation: { type: 'Point' as const, coordinates: [-58.449, -34.573] },
        institution: aleman._id,
        dateOfAdmission: new Date('2026-06-05T20:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Constitucion ──────────────────────────────────────────────────────
      {
        estimatedAgeMin: 55,
        estimatedAgeMax: 65,
        gender: Gender.FEMALE,
        height: 1.55,
        distinctiveFeatures: 'Cabello gris, permanente. Vestía ropa de colores oscuros con cartera negra. Desorientada, repite constantemente un nombre de pila.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Entre Ríos 1200, Constitucion',
        neighborhood: 'Constitucion',
        geoLocation: { type: 'Point' as const, coordinates: [-58.382, -34.624] },
        institution: clinicas._id,
        dateOfAdmission: new Date('2026-06-04T12:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        assignedTo: 'EAAF',
        createdBy: sofia._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 30,
        estimatedAgeMax: 40,
        gender: Gender.MALE,
        height: 1.69,
        weight: 75,
        distinctiveFeatures: 'Cicatriz larga en el brazo izquierdo. Cabello oscuro corto. Sin documentación. Vestía jean y campera negra.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Garay 100, Constitucion',
        neighborhood: 'Constitucion',
        geoLocation: { type: 'Point' as const, coordinates: [-58.38, -34.625] },
        institution: favaloro._id,
        dateOfAdmission: new Date('2026-06-09T02:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Flores ────────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 50,
        estimatedAgeMax: 60,
        gender: Gender.MALE,
        height: 1.71,
        weight: 88,
        distinctiveFeatures: 'Contextura robusta. Cabello negro con canas. Bigote oscuro. Tatuaje de virgen María en el antebrazo. Vestía camisa de trabajo y pantalón de jean.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Rivadavia 7100, Flores',
        neighborhood: 'Flores',
        geoLocation: { type: 'Point' as const, coordinates: [-58.462, -34.630] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-06T16:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 16,
        estimatedAgeMax: 22,
        gender: Gender.FEMALE,
        height: 1.67,
        distinctiveFeatures: 'Cabello negro muy largo. Ropa oscura tipo gótico. Múltiples anillos en los dedos. Tatuaje de luna en la muñeca.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Carabobo 400, Flores',
        neighborhood: 'Flores',
        geoLocation: { type: 'Point' as const, coordinates: [-58.461, -34.631] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-10T23:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Floresta ──────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 40,
        estimatedAgeMax: 50,
        gender: Gender.MALE,
        height: 1.74,
        weight: 80,
        distinctiveFeatures: 'Cabello castaño con entradas. Lentes de contacto (ojos de diferentes colores, uno verde y uno azul). Vestía ropa de oficina.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Gaona 4200, Floresta',
        neighborhood: 'Floresta',
        geoLocation: { type: 'Point' as const, coordinates: [-58.479, -34.628] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-08T18:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Liniers ───────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 45,
        estimatedAgeMax: 55,
        gender: Gender.FEMALE,
        height: 1.60,
        weight: 70,
        distinctiveFeatures: 'Cabello negro lacio, largo. Piel morena. Vestía pollera larga floreada y blusa blanca. Hablaba en voz baja, idioma inidentificado.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Rivadavia 11200, Liniers',
        neighborhood: 'Liniers',
        geoLocation: { type: 'Point' as const, coordinates: [-58.521, -34.636] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-07T14:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        assignedTo: 'SIFEBU',
        createdBy: laura._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 25,
        estimatedAgeMax: 35,
        gender: Gender.MALE,
        height: 1.77,
        distinctiveFeatures: 'Tatuajes en ambos brazos (mangas completas). Cabello rapado. Pendiente en oreja derecha. Vestía remera sin mangas y jogging.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. General Paz 1200, Liniers',
        neighborhood: 'Liniers',
        geoLocation: { type: 'Point' as const, coordinates: [-58.522, -34.637] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-11T01:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Mataderos ─────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 35,
        estimatedAgeMax: 45,
        gender: Gender.MALE,
        height: 1.69,
        weight: 85,
        distinctiveFeatures: 'Cicatriz quirúrgica en la rodilla derecha. Cabello oscuro corto. Contextura robusta. Vestía ropa de trabajo sucia.',
        consciousnessLevel: ConsciousnessLevel.UNCONSCIOUS,
        address: 'Av. Eva Perón 5600, Mataderos',
        neighborhood: 'Mataderos',
        geoLocation: { type: 'Point' as const, coordinates: [-58.504, -34.655] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-03T06:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Monserrat ─────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 20,
        estimatedAgeMax: 28,
        gender: Gender.FEMALE,
        height: 1.68,
        weight: 58,
        distinctiveFeatures: 'Cabello negro con mechas rubias. Vestía uniforme de empleada. Tatuaje de estrella en el tobillo. Desorientada al llegar.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Belgrano 1746, Monserrat',
        neighborhood: 'Monserrat',
        geoLocation: { type: 'Point' as const, coordinates: [-58.3929, -34.6128] },
        institution: favaloro._id,
        dateOfAdmission: new Date('2026-06-05T09:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 60,
        estimatedAgeMax: 70,
        gender: Gender.MALE,
        distinctiveFeatures: 'Adulto mayor de tez blanca. Cabello blanco escaso. Vestía traje oscuro formal. Usaba corbata. Aparentaba haber estado en un evento formal.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Hipólito Yrigoyen 800, Monserrat',
        neighborhood: 'Monserrat',
        geoLocation: { type: 'Point' as const, coordinates: [-58.382, -34.612] },
        institution: favaloro._id,
        dateOfAdmission: new Date('2026-06-09T21:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Ministerio Público Fiscal CABA',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Monte Castro ──────────────────────────────────────────────────────
      {
        estimatedAgeMin: 30,
        estimatedAgeMax: 40,
        gender: Gender.FEMALE,
        height: 1.64,
        weight: 63,
        distinctiveFeatures: 'Cabello castaño, media melena. Cicatriz en la frente. Vestía jogging azul marino y zapatillas blancas.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Juan B. Justo 9000, Monte Castro',
        neighborhood: 'Monte Castro',
        geoLocation: { type: 'Point' as const, coordinates: [-58.499, -34.623] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-08T07:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Nueva Pompeya ─────────────────────────────────────────────────────
      {
        estimatedAgeMin: 40,
        estimatedAgeMax: 50,
        gender: Gender.MALE,
        height: 1.67,
        weight: 76,
        distinctiveFeatures: 'Piel oscura. Cabello corto con canas. Cicatriz en el labio superior. Vestía camisa de cuadros y pantalón de trabajo.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Sáenz 200, Nueva Pompeya',
        neighborhood: 'Nueva Pompeya',
        geoLocation: { type: 'Point' as const, coordinates: [-58.406, -34.658] },
        institution: britanico._id,
        dateOfAdmission: new Date('2026-06-06T10:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Nuñez ─────────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 25,
        estimatedAgeMax: 35,
        gender: Gender.FEMALE,
        height: 1.70,
        weight: 60,
        distinctiveFeatures: 'Cabello rubio natural. Vestía ropa deportiva de alta calidad. Casco de ciclismo en la cabeza al llegar. Fractura de radio.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Libertador 7000, Nuñez',
        neighborhood: 'Nuñez',
        geoLocation: { type: 'Point' as const, coordinates: [-58.474, -34.546] },
        institution: aleman._id,
        dateOfAdmission: new Date('2026-06-07T17:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        createdBy: sofia._id,
        identifyingPhotos: [],
      },

      // ── Palermo (adicional) ───────────────────────────────────────────────
      {
        estimatedAgeMin: 40,
        estimatedAgeMax: 50,
        gender: Gender.MALE,
        height: 1.75,
        weight: 78,
        distinctiveFeatures: 'Contextura media. Barba entrecana bien cuidada. Vestía ropa de diseñador. Reloj de lujo en la muñeca. Sin documentación.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. del Libertador 3000, Palermo',
        neighborhood: 'Palermo',
        geoLocation: { type: 'Point' as const, coordinates: [-58.41, -34.575] },
        institution: bazterrica._id,
        dateOfAdmission: new Date('2026-06-08T23:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Ministerio Público Fiscal CABA',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Parque Avellaneda ─────────────────────────────────────────────────
      {
        estimatedAgeMin: 20,
        estimatedAgeMax: 30,
        gender: Gender.MALE,
        height: 1.72,
        distinctiveFeatures: 'Cabello negro liso corto. Tatuaje de serpiente en el cuello. Vestía ropa deportiva negra. Sin calzado.',
        consciousnessLevel: ConsciousnessLevel.UNCONSCIOUS,
        address: 'Av. Directorio 4600, Parque Avellaneda',
        neighborhood: 'Parque Avellaneda',
        geoLocation: { type: 'Point' as const, coordinates: [-58.472, -34.651] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-04T04:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Parque Chacabuco ──────────────────────────────────────────────────
      {
        estimatedAgeMin: 50,
        estimatedAgeMax: 60,
        gender: Gender.FEMALE,
        height: 1.57,
        weight: 68,
        distinctiveFeatures: 'Cabello oscuro con mucho gris, largo. Vestía delantal de verdulera. Manos con callos de trabajo. Desorientada.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Asamblea 300, Parque Chacabuco',
        neighborhood: 'Parque Chacabuco',
        geoLocation: { type: 'Point' as const, coordinates: [-58.432, -34.638] },
        institution: clinicas._id,
        dateOfAdmission: new Date('2026-06-05T11:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Parque Chas ───────────────────────────────────────────────────────
      {
        estimatedAgeMin: 35,
        estimatedAgeMax: 45,
        gender: Gender.MALE,
        height: 1.78,
        weight: 76,
        distinctiveFeatures: 'Cabello castaño largo atado. Anteojos rectangulares de armazón oscura. Vestía ropa casual. Computadora portátil en la mochila.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. de los Incas 4800, Parque Chas',
        neighborhood: 'Parque Chas',
        geoLocation: { type: 'Point' as const, coordinates: [-58.478, -34.574] },
        institution: aleman._id,
        dateOfAdmission: new Date('2026-06-09T16:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        createdBy: sofia._id,
        identifyingPhotos: [],
      },

      // ── Parque Patricios ──────────────────────────────────────────────────
      {
        estimatedAgeMin: 28,
        estimatedAgeMax: 38,
        gender: Gender.MALE,
        height: 1.74,
        weight: 72,
        distinctiveFeatures: 'Piel morena. Cabello rizado corto. Tatuaje de fecha en el cuello. Vestía remera deportiva roja y pantalón negro.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Caseros 3200, Parque Patricios',
        neighborhood: 'Parque Patricios',
        geoLocation: { type: 'Point' as const, coordinates: [-58.393, -34.639] },
        institution: britanico._id,
        dateOfAdmission: new Date('2026-06-07T21:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Paternal ──────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 30,
        estimatedAgeMax: 40,
        gender: Gender.FEMALE,
        height: 1.63,
        weight: 58,
        distinctiveFeatures: 'Cabello oscuro corto con flequillo. Vestía uniforme de enfermera azul. Tatuaje de mariposa en la muñeca. Muy agitada al llegar.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Warnes 2600, Paternal',
        neighborhood: 'Paternal',
        geoLocation: { type: 'Point' as const, coordinates: [-58.467, -34.598] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-06T20:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Puerto Madero ─────────────────────────────────────────────────────
      {
        estimatedAgeMin: 25,
        estimatedAgeMax: 33,
        gender: Gender.MALE,
        height: 1.83,
        weight: 78,
        distinctiveFeatures: 'Contextura atlética. Cabello castaño oscuro, corte moderno. Vestía traje oscuro de alta calidad, sin corbata. Zapatos de cuero caros.',
        consciousnessLevel: ConsciousnessLevel.UNCONSCIOUS,
        address: 'Av. Alicia Moreau de Justo 1000, Puerto Madero',
        neighborhood: 'Puerto Madero',
        geoLocation: { type: 'Point' as const, coordinates: [-58.363, -34.610] },
        institution: favaloro._id,
        dateOfAdmission: new Date('2026-06-04T01:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Recoleta (adicional) ──────────────────────────────────────────────
      {
        estimatedAgeMin: 45,
        estimatedAgeMax: 55,
        gender: Gender.FEMALE,
        height: 1.65,
        weight: 60,
        distinctiveFeatures: 'Cabello oscuro corto, muy bien arreglado. Vestía abrigo largo de lana gris. Collar de perlas. Aparentaba estar en estado de shock.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Pueyrredón 1640, Recoleta',
        neighborhood: 'Recoleta',
        geoLocation: { type: 'Point' as const, coordinates: [-58.3993, -34.5904] },
        institution: otamendi._id,
        dateOfAdmission: new Date('2026-06-06T18:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        assignedTo: 'EAAF',
        createdBy: sofia._id,
        identifyingPhotos: [],
      },

      // ── Retiro ────────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 18,
        estimatedAgeMax: 25,
        gender: Gender.MALE,
        distinctiveFeatures: 'Cabello oscuro, desaliñado. Ropa muy deteriorada, sucia. Cicatrices en ambos brazos (marcas de jeringas). Ingresó desmayado en la terminal de ómnibus.',
        consciousnessLevel: ConsciousnessLevel.SEDATED,
        address: 'Av. Antártida Argentina 1400, Retiro',
        neighborhood: 'Retiro',
        geoLocation: { type: 'Point' as const, coordinates: [-58.375, -34.591] },
        institution: clinicas._id,
        dateOfAdmission: new Date('2026-06-02T16:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Ministerio Público Fiscal - Procuración General de la Nación',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 40,
        estimatedAgeMax: 50,
        gender: Gender.FEMALE,
        height: 1.62,
        weight: 58,
        distinctiveFeatures: 'Piel triguena. Cabello negro lacio, largo. Vestía pollera y blusa de trabajo. Cartera con documentación en idioma no identificado.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Calle Florida 1100, Retiro',
        neighborhood: 'Retiro',
        geoLocation: { type: 'Point' as const, coordinates: [-58.374, -34.592] },
        institution: clinicas._id,
        dateOfAdmission: new Date('2026-06-10T13:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        assignedTo: 'SIFEBU',
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Saavedra ──────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 55,
        estimatedAgeMax: 65,
        gender: Gender.MALE,
        height: 1.70,
        weight: 78,
        distinctiveFeatures: 'Cabello gris, bien peinado. Bigote gris. Vestía ropa de deporte azul. Zapatillas blancas. Desorientado.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Balbín 3500, Saavedra',
        neighborhood: 'Saavedra',
        geoLocation: { type: 'Point' as const, coordinates: [-58.488, -34.549] },
        institution: aleman._id,
        dateOfAdmission: new Date('2026-06-08T09:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        assignedTo: 'EAAF',
        createdBy: sofia._id,
        identifyingPhotos: [],
      },

      // ── San Cristobal ─────────────────────────────────────────────────────
      {
        estimatedAgeMin: 35,
        estimatedAgeMax: 45,
        gender: Gender.FEMALE,
        height: 1.59,
        weight: 65,
        distinctiveFeatures: 'Cabello castaño, rizado, largo. Vestía delantal de peluquería. Tijeras en el bolsillo delantero. Aparentemente confundida.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Independencia 3500, San Cristobal',
        neighborhood: 'San Cristobal',
        geoLocation: { type: 'Point' as const, coordinates: [-58.393, -34.618] },
        institution: clinicas._id,
        dateOfAdmission: new Date('2026-06-07T13:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── San Nicolas ───────────────────────────────────────────────────────
      {
        estimatedAgeMin: 28,
        estimatedAgeMax: 38,
        gender: Gender.MALE,
        height: 1.76,
        weight: 73,
        distinctiveFeatures: 'Cabello castaño, corte prolijo. Vestía traje gris de oficina. Cartera de cuero negra. Sin documentación. Marcas de golpes en el rostro.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Corrientes 1400, San Nicolas',
        neighborhood: 'San Nicolas',
        geoLocation: { type: 'Point' as const, coordinates: [-58.38, -34.601] },
        institution: favaloro._id,
        dateOfAdmission: new Date('2026-06-05T22:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── San Telmo ─────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 28,
        estimatedAgeMax: 36,
        gender: Gender.FEMALE,
        height: 1.67,
        weight: 57,
        distinctiveFeatures: 'Cabello castaño oscuro, largo. Vestía vestido floreado y sandalias. Tatuaje de pluma de tinta en el costado del torso. Muy callada.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Defensa 1200, San Telmo',
        neighborhood: 'San Telmo',
        geoLocation: { type: 'Point' as const, coordinates: [-58.370, -34.622] },
        institution: britanico._id,
        dateOfAdmission: new Date('2026-06-06T21:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 50,
        estimatedAgeMax: 60,
        gender: Gender.MALE,
        distinctiveFeatures: 'Barba larga canosa. Vestía abrigo largo oscuro muy gastado. Calzado deteriorado. Aparenta vivir en situación de calle.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Brasil 300, San Telmo',
        neighborhood: 'San Telmo',
        geoLocation: { type: 'Point' as const, coordinates: [-58.369, -34.623] },
        institution: favaloro._id,
        dateOfAdmission: new Date('2026-06-09T07:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'EAAF',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Velez Sarsfield ───────────────────────────────────────────────────
      {
        estimatedAgeMin: 40,
        estimatedAgeMax: 50,
        gender: Gender.MALE,
        height: 1.73,
        weight: 82,
        distinctiveFeatures: 'Cabello oscuro, entradas pronunciadas. Cicatriz de quemadura en el hombro izquierdo. Vestía ropa de mecánico con manchas de aceite.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Juan B. Justo 7600, Velez Sarsfield',
        neighborhood: 'Velez Sarsfield',
        geoLocation: { type: 'Point' as const, coordinates: [-58.493, -34.637] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-07T12:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Versalles ─────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 60,
        estimatedAgeMax: 70,
        gender: Gender.FEMALE,
        distinctiveFeatures: 'Cabello blanco muy corto. Vestía ropa de jardín (delantal verde, guantes de trabajo). Desorientada. Muy ansiosa.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Varela 4700, Versalles',
        neighborhood: 'Versalles',
        geoLocation: { type: 'Point' as const, coordinates: [-58.513, -34.629] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-10T15:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        assignedTo: 'EAAF',
        createdBy: sofia._id,
        identifyingPhotos: [],
      },

      // ── Villa Crespo ──────────────────────────────────────────────────────
      {
        estimatedAgeMin: 17,
        estimatedAgeMax: 22,
        gender: Gender.FEMALE,
        height: 1.68,
        distinctiveFeatures: 'Cabello corto azulado (teñido). Aretes grandes circulares. Vestía remera de banda de rock y pantalón de cuero. Tatuaje de corazón en el cuello.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Corrientes 5000, Villa Crespo',
        neighborhood: 'Villa Crespo',
        geoLocation: { type: 'Point' as const, coordinates: [-58.435, -34.593] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-08T00:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 45,
        estimatedAgeMax: 55,
        gender: Gender.MALE,
        height: 1.71,
        weight: 82,
        distinctiveFeatures: 'Cabello castaño con canas. Barba corta entrecana. Vestía ropa de trabajo de construcción. Lesión en la cabeza.',
        consciousnessLevel: ConsciousnessLevel.SEDATED,
        address: 'Thames 700, Villa Crespo',
        neighborhood: 'Villa Crespo',
        geoLocation: { type: 'Point' as const, coordinates: [-58.434, -34.592] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-11T10:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Villa Del Parque ──────────────────────────────────────────────────
      {
        estimatedAgeMin: 30,
        estimatedAgeMax: 40,
        gender: Gender.FEMALE,
        height: 1.64,
        weight: 61,
        distinctiveFeatures: 'Cabello castaño, liso, largo. Vestía ropa de enfermería verde. Muy callada, no responde preguntas.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Francisco Beiró 4500, Villa Del Parque',
        neighborhood: 'Villa Del Parque',
        geoLocation: { type: 'Point' as const, coordinates: [-58.479, -34.609] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-09T08:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Villa Devoto ──────────────────────────────────────────────────────
      {
        estimatedAgeMin: 60,
        estimatedAgeMax: 70,
        gender: Gender.MALE,
        distinctiveFeatures: 'Adulto mayor. Cabello blanco peinado. Vestía bata de dormir celeste y pantuflas. Salió de su casa en pijama. Desorientado.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Francisco Beiró 5200, Villa Devoto',
        neighborhood: 'Villa Devoto',
        geoLocation: { type: 'Point' as const, coordinates: [-58.499, -34.607] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-07T05:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        assignedTo: 'EAAF',
        createdBy: sofia._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 35,
        estimatedAgeMax: 45,
        gender: Gender.FEMALE,
        height: 1.66,
        weight: 64,
        distinctiveFeatures: 'Cabello oscuro con mechas, a los hombros. Vestía vestido de fiesta color vino. Maquillaje corrido. Perdió su cartera.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Tinogasta 2800, Villa Devoto',
        neighborhood: 'Villa Devoto',
        geoLocation: { type: 'Point' as const, coordinates: [-58.500, -34.608] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-08T04:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Villa Gral. Mitre ─────────────────────────────────────────────────
      {
        estimatedAgeMin: 45,
        estimatedAgeMax: 55,
        gender: Gender.MALE,
        height: 1.72,
        weight: 86,
        distinctiveFeatures: 'Contextura robusta. Cabello oscuro rapado. Cicatriz antigua en el abdomen (apéndice). Vestía ropa deportiva azul.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Gaona 3100, Villa Gral. Mitre',
        neighborhood: 'Villa Gral. Mitre',
        geoLocation: { type: 'Point' as const, coordinates: [-58.475, -34.614] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-10T09:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Villa Lugano ──────────────────────────────────────────────────────
      {
        estimatedAgeMin: 20,
        estimatedAgeMax: 30,
        gender: Gender.MALE,
        height: 1.73,
        distinctiveFeatures: 'Piel oscura. Cabello rizado. Tatuaje de número en el cuello (222). Vestía ropa deportiva negra y dorada.',
        consciousnessLevel: ConsciousnessLevel.UNCONSCIOUS,
        address: 'Av. Escalada 500, Villa Lugano',
        neighborhood: 'Villa Lugano',
        geoLocation: { type: 'Point' as const, coordinates: [-58.478, -34.672] },
        institution: britanico._id,
        dateOfAdmission: new Date('2026-06-03T01:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 35,
        estimatedAgeMax: 45,
        gender: Gender.FEMALE,
        height: 1.58,
        weight: 62,
        distinctiveFeatures: 'Cabello negro liso. Vestía ropa de trabajo de limpieza. Pequeña cicatriz en la ceja derecha. Hablaba pero no daba información coherente.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Cruz 3900, Villa Lugano',
        neighborhood: 'Villa Lugano',
        geoLocation: { type: 'Point' as const, coordinates: [-58.479, -34.673] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-08T12:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Villa Luro ────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 55,
        estimatedAgeMax: 65,
        gender: Gender.MALE,
        height: 1.68,
        weight: 74,
        distinctiveFeatures: 'Cabello gris escaso, calvo en la coronilla. Lentes de aumento gruesos. Vestía camisa de manga larga azul y pantalón de vestir. Desorientado.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Rivadavia 9600, Villa Luro',
        neighborhood: 'Villa Luro',
        geoLocation: { type: 'Point' as const, coordinates: [-58.503, -34.637] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-06T14:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        assignedTo: 'EAAF',
        createdBy: sofia._id,
        identifyingPhotos: [],
      },

      // ── Villa Ortuzar ─────────────────────────────────────────────────────
      {
        estimatedAgeMin: 25,
        estimatedAgeMax: 35,
        gender: Gender.FEMALE,
        height: 1.70,
        weight: 59,
        distinctiveFeatures: 'Cabello castaño claro, rizado, largo. Vestía ropa artística. Mancha de pintura en las manos y ropa. Muy callada.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Dorrego 2900, Villa Ortuzar',
        neighborhood: 'Villa Ortuzar',
        geoLocation: { type: 'Point' as const, coordinates: [-58.468, -34.581] },
        institution: aleman._id,
        dateOfAdmission: new Date('2026-06-09T17:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Villa Pueyrredon ──────────────────────────────────────────────────
      {
        estimatedAgeMin: 45,
        estimatedAgeMax: 55,
        gender: Gender.MALE,
        height: 1.74,
        weight: 79,
        distinctiveFeatures: 'Cabello castaño canoso. Tatuaje de mapa de Argentina en el pecho. Vestía ropa de fútbol sala. Lesión en el tobillo.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. de los Incas 5100, Villa Pueyrredon',
        neighborhood: 'Villa Pueyrredon',
        geoLocation: { type: 'Point' as const, coordinates: [-58.494, -34.592] },
        institution: aleman._id,
        dateOfAdmission: new Date('2026-06-10T20:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Villa Real ────────────────────────────────────────────────────────
      {
        estimatedAgeMin: 30,
        estimatedAgeMax: 40,
        gender: Gender.FEMALE,
        height: 1.61,
        weight: 57,
        distinctiveFeatures: 'Cabello oscuro, mediana melena. Pendientes de aro dorados. Vestía ropa de trabajo administrativo. Sin documentación.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Bonorino 3600, Villa Real',
        neighborhood: 'Villa Real',
        geoLocation: { type: 'Point' as const, coordinates: [-58.519, -34.634] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-08T08:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Villa Riachuelo ───────────────────────────────────────────────────
      {
        estimatedAgeMin: 40,
        estimatedAgeMax: 50,
        gender: Gender.MALE,
        height: 1.66,
        weight: 73,
        distinctiveFeatures: 'Cabello oscuro escaso. Tatuaje de dragón en la espalda (visible por la ropa rasgada). Vestía ropa muy deteriorada. Quemaduras menores.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Riachuelo 3000, Villa Riachuelo',
        neighborhood: 'Villa Riachuelo',
        geoLocation: { type: 'Point' as const, coordinates: [-58.448, -34.684] },
        institution: britanico._id,
        dateOfAdmission: new Date('2026-06-05T08:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },

      // ── Villa Santa Rita ──────────────────────────────────────────────────
      {
        estimatedAgeMin: 35,
        estimatedAgeMax: 45,
        gender: Gender.FEMALE,
        height: 1.62,
        weight: 66,
        distinctiveFeatures: 'Cabello castaño, corte en capas. Anteojos de armazón roja. Vestía ropa casual. Tatuaje de flores en el tobillo izquierdo.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Ramón Falcón 6000, Villa Santa Rita',
        neighborhood: 'Villa Santa Rita',
        geoLocation: { type: 'Point' as const, coordinates: [-58.483, -34.620] },
        institution: italiano._id,
        dateOfAdmission: new Date('2026-06-09T11:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Villa Soldati ─────────────────────────────────────────────────────
      {
        estimatedAgeMin: 25,
        estimatedAgeMax: 35,
        gender: Gender.MALE,
        height: 1.76,
        weight: 71,
        distinctiveFeatures: 'Piel morena oscura. Cabello muy corto. Cicatriz de bala en el muslo izquierdo. Vestía ropa de trabajo de construcción.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Escalada 2000, Villa Soldati',
        neighborhood: 'Villa Soldati',
        geoLocation: { type: 'Point' as const, coordinates: [-58.436, -34.673] },
        institution: britanico._id,
        dateOfAdmission: new Date('2026-06-07T09:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.DOCTOR, Gender.MALE, `${carlos.firstName} ${carlos.lastName}`),
        assignedTo: 'Policía de la Ciudad',
        createdBy: carlos._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 45,
        estimatedAgeMax: 55,
        gender: Gender.FEMALE,
        height: 1.56,
        distinctiveFeatures: 'Cabello oscuro canoso. Vestía delantal de cocina. Manos con callos. Desorientada, habla español con acento marcado.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Cnel. Roca 4200, Villa Soldati',
        neighborhood: 'Villa Soldati',
        geoLocation: { type: 'Point' as const, coordinates: [-58.437, -34.674] },
        institution: guemes._id,
        dateOfAdmission: new Date('2026-06-10T10:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        assignedTo: 'SIFEBU',
        createdBy: laura._id,
        identifyingPhotos: [],
      },

      // ── Villa Urquiza ─────────────────────────────────────────────────────
      {
        estimatedAgeMin: 45,
        estimatedAgeMax: 55,
        gender: Gender.MALE,
        height: 1.74,
        weight: 80,
        distinctiveFeatures: 'Cabello oscuro con canas, corto. Vestía ropa deportiva de calidad. Sin calzado. Aparentaba haber estado corriendo.',
        consciousnessLevel: ConsciousnessLevel.CONSCIOUS,
        address: 'Av. Triunvirato 4500, Villa Urquiza',
        neighborhood: 'Villa Urquiza',
        geoLocation: { type: 'Point' as const, coordinates: [-58.483, -34.572] },
        institution: aleman._id,
        dateOfAdmission: new Date('2026-06-08T07:30:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.PSYCHOLOGIST, Gender.FEMALE, `${sofia.firstName} ${sofia.lastName}`),
        createdBy: sofia._id,
        identifyingPhotos: [],
      },
      {
        estimatedAgeMin: 22,
        estimatedAgeMax: 30,
        gender: Gender.FEMALE,
        height: 1.69,
        weight: 56,
        distinctiveFeatures: 'Cabello rubio largo. Vestía uniforme de azafata. Sin documentación. Estado de shock.',
        consciousnessLevel: ConsciousnessLevel.DISORIENTED,
        address: 'Av. Álvarez Thomas 3000, Villa Urquiza',
        neighborhood: 'Villa Urquiza',
        geoLocation: { type: 'Point' as const, coordinates: [-58.484, -34.573] },
        institution: otamendi._id,
        dateOfAdmission: new Date('2026-06-10T18:00:00'),
        status: PersonStatus.UNIDENTIFIED,
        reportedBy: buildReportedBy(UserRole.NURSE, Gender.FEMALE, `${laura.firstName} ${laura.lastName}`),
        assignedTo: 'Ministerio Público Fiscal CABA',
        createdBy: laura._id,
        identifyingPhotos: [],
      },
    ];

    await PersonModel.insertMany(persons);
    await SeederLog.create({ _id: SEEDER_ID });

    logger.info(`Seeder "${SEEDER_ID}" completed — ${persons.length} persons inserted`);
  } catch (err) {
    logger.error(err, `Seeder "${SEEDER_ID}" failed`);
    throw err;
  }
};
